### ISSUE TITLE
FeedService/Video.mp4 request fails

### ISSUE THREAD

**Issue by qtlin** [i3arnon/YouCast#59] opened 2020-07-21 14:56 UTC
It suddenly started returning 404 around midnight GMT today. FeedService/GetUserFeed is working as usual. YoutubeExplode has been modified several hours ago with a comment indicating resolving an error caused by a recent YouTube change. Please update.

**Comment by mrDLSable** [comment] 2020-07-21 15:05
I'm having this problem as well.

21 Jul 2020 16:56:23 qtlin <notifications@github.com>:

**Comment by sch1308** [comment] 2020-07-22 19:56
I am having the same problem, my youtube api is still registering hits so that part is still working.

**Comment by qtlin** [comment] 2020-07-23 02:11
I updated YoutubeExplode version in src\Service\Service.csproj from 5.0.4 to 5.1.2 and recompiled. Seems to work now.
If there are any VisualStudio experts here it would be nice to post some kind of easy to follow recompile instructions, preferably without a need to use any UI, since @i3arnon apparently is busy with his primary occupation and not a frequent visitor here.

**Comment by i3arnon** [comment] 2020-07-23 10:16
Updated : https://github.com/i3arnon/YouCast/releases/tag/2.13.0
Thanks for letting me know.

**Comment by qtlin** [comment] 2020-07-28 13:17
It is the same again, discussion is [here](https://github.com/Tyrrrz/YoutubeExplode/issues/427).

**Comment by qtlin** [comment] 2020-07-31 15:27
YoutubeExplode 5.1.3 has been released. Is there a way to set up an automated process to grab latest YoutubeExplode and release YouCast?

**Comment by i3arnon** [comment] 2020-07-31 16:03
Updated: https://github.com/i3arnon/YouCast/releases/tag/2.14.0

**Comment by qtlin** [comment] 2020-09-13 18:30
YoutubeExplode 5.1.5 has been released, contains several updates for YouTube changes.

**Comment by IWScout** [comment] 2020-09-22 15:11
My feeds have been failing since Sept 13.  Is this the issue?

**Comment by qtlin** [comment] 2020-09-22 16:05
Not sure, I think I am still on 2.14.0 and all is working.

**Comment by IWScout** [comment] 2020-09-22 16:18
Thanks.  I'll look closer at my configuration, assuming the issue is mine.

**Comment by IWScout** [comment] 2020-09-22 17:42
Yep.  The issue was mine.  Solved.

**Comment by kane2742** [comment] 2020-10-01 23:55
I'm getting 404s when I try to download again (for the past few days). I see that [YouTubeExplode](https://github.com/Tyrrrz/YoutubeExplode) was updated again recently, so maybe time to incorporate that update?

**Comment by qtlin** [comment] 2020-10-02 00:15
Mine still works as is but I don't recall what YouTubeExplode version is included, copied on 7/31.

**Comment by kane2742** [comment] 2020-10-03 01:50
@IWScout : How did you fix your issue? I'm wondering if mine has the same cause, if it's the YouTubeExplode version, or something else.

**Comment by IWScout** [comment] 2020-10-03 03:00
It was something else for me.  I checked and saved all the settings, rebooted the service.  No clue what was causing it, but works fine now.

**Comment by kane2742** [comment] 2020-10-07 00:19
After a few days of not working (updating feeds, but getting 404s for every download), my downloads are working again. I'm not sure why – I didn't change anything in YouCast or anything else I can think of that might affect it (like my router). Weird.

**Comment by i3arnon** [comment] 2020-10-20 11:19
> I see that [YouTubeExplode](https://github.com/Tyrrrz/YoutubeExplode) was updated again recently, so maybe time to incorporate that update?

Updated: https://github.com/i3arnon/YouCast/releases/tag/2.15.0

**Comment by IWScout** [comment] 2020-11-18 19:21
I started having issues yesterday.  The feeds are updating fine, but I get 404 - requested url could not be found... on every download.  I've checked all the settings, rebooted multiple times, and tried both v2.16 and 2.17.  Still no luck.  Is anyone else having issues?

**Comment by Loonygoose** [comment] 2020-11-21 11:52
Yep, I just noticed the same issue cropping up as well

**Comment by superfutzi** [comment] 2020-11-22 10:51
Same problem on my side, updating works fine but I get a 404 on every attempt to download an episode.

**Comment by kane2742** [comment] 2020-11-27 02:43
I wasn't having this issue when the last three comments were made, but I am now: feeds update, but downloads attempts result in 404s.

**Comment by Loonygoose** [comment] 2020-12-04 02:28
Thanks for the 2.18 release. Problem fixed.

**Comment by qtlin** [comment] 2020-12-05 21:44
Seems like YouTube changed something again today. List works but items don't. Running latest.

**Comment by Loonygoose** [comment] 2020-12-07 06:31
Mine appears to still be working for now

**Comment by mrDLSable** [comment] 2021-01-15 19:13
The videos have started to fail to download once again...

**Comment by kane2742** [comment] 2021-01-18 18:30
I'm getting 404s on downloads again. Feeds still update, though. I tried closing YouCast, restarting my computer, and restarting YouCast, but that doesn't seem to have made a difference..

**Comment by maxol18** [comment] 2021-01-19 06:43
Ho,

For me if Worked this morning.

Maybe you need to update the developer key ?

**Comment by kane2742** [comment] 2021-01-19 18:36
I regenerated my API key, replaced it in YouCast, and waited a bit before I tried again. Same result: Feeds update, but episodes don't download, they just give me 404s. I've had this issue a few times before. Sometimes it seems to fix itself within a few days, but I've never figured out why. Other times, it doesn't work until the next version (usually having to do with a new version of YouTubeExplode, but the [latest version of that](https://www.nuget.org/packages/YoutubeExplode) is from two months ago). If other people aren't having issues right now, I'm guessing this will be a case where mine works again in a few days. I wish I could figure out what causes that, and how to fix it instead of just waiting. Does anybody have any other troubleshooting tips, (besides the obvious – restarting – which I already did)?

**Comment by Loonygoose** [comment] 2021-01-19 21:20
Mine started failing a few days ago as well, but suddenly worked again this morning with no changes. Weird.

**Comment by qtlin** [comment] 2021-01-19 21:35
You may be experiencing  https://github.com/Tyrrrz/YoutubeExplode/issues/489 since I had exactly the same symptoms.

**Comment by mrDLSable** [comment] 2021-02-09 12:24
It's 404-ing for me again on episode downloads... The podcasts update properly but the downloads fail...

**Comment by kane2742** [comment] 2021-02-09 23:35
@mrDLSable I was having the same issue a few weeks ago, but I got it working eventually (and forgot to post an update here). For me, it looks like the issue was too many requests from my IP address, possibly because I had recently added several subscriptions. I found out by accident that it works when I use a VPN. (I was testing out the free version of ProtonVPN when an automatic update of my subscriptions started, and ran successfully.) Ever since then, it works whenever I'm connected to the VPN, but it's hit-or-miss when I'm not.

**Comment by mrDLSable** [comment] 2021-02-10 06:19
@kane2742 I just installed private internet access on my phone, but it still 404s. Or did you mean on the server that runs youcast?

**Comment by kane2742** [comment] 2021-02-10 16:00
@mrDLSable I guess I should have been more specific. For me, the VPN is only active on the machine actually running YouCast (in my case, my PC), not the one downloading the videos (in my case, an Android tablet). Looks like you figured it out, though.

**Closed** 2021-08-18 22:07 UTC
